FROM python:3.11-slim
WORKDIR /app

# Install dependencies
COPY python/server/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

RUN mkdir -p /app/proto /app/gen
# Copy proto and generate code
COPY proto/project1.proto /app/proto/project1.proto

RUN python -m grpc_tools.protoc \
    -I /app/proto \
    --python_out=/app/gen \
    --grpc_python_out=/app/gen \
    /app/proto/project1.proto

# Copy client code
COPY python/client/client.py /app/client.py

ENV PYTHONPATH="/app/gen"

CMD ["python","-u", "client.py"]