FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /build

COPY java/ /build/
RUN mvn -q -DskipTests clean package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /build/target/grpc-crosslang-1.0.0.jar /app/app.jar

ENV SERVER_HOST=localhost
ENV SERVER_PORT=50051
ENV NAME=Evelyn
ENV CLIENT_LANGUAGE=java

CMD ["java", "-cp", "/app/app.jar", "cse5306.project1.ClientMain"]
